2023-07-09 19:42:27,023  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.impl.jdbc.DBConnectionException: No datasource named 'Replication' is registered with this manager. Available datasources are: []
2023-07-09 19:42:30,025  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.impl.jdbc.DBConnectionException: No datasource named 'Replication' is registered with this manager. Available datasources are: []
2023-07-09 19:42:33,027  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.impl.jdbc.DBConnectionException: No datasource named 'Replication' is registered with this manager. Available datasources are: []
2023-07-09 19:42:36,030  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.impl.jdbc.DBConnectionException: No datasource named 'Replication' is registered with this manager. Available datasources are: []
2023-07-09 19:42:39,032 ERROR [Replication Processor] dtv.data2.replication.dtximpl.ReplicationProcessor - Unpexpected exception caught in ReplicationProcessor main loop. We will attempt to continue.
dtv.data2.replication.ReplicationException: Unable to obtain datasource for replication queue [Replication]
	at dtv.data2.replication.dtximpl.ReplicationQueueAccessor.getConnection(ReplicationQueueAccessor.java:614) ~[dtv-data2.jar:22.0.0.0.20230127185818]
	at dtv.data2.replication.dtximpl.ReplicationQueueAccessor.queryNonFailedRecCount(ReplicationQueueAccessor.java:294) ~[dtv-data2.jar:22.0.0.0.20230127185818]
	at dtv.data2.replication.dtximpl.ReplicationProcessor.run(ReplicationProcessor.java:172) ~[dtv-data2.jar:22.0.0.0.20230127185818]
2023-07-09 19:59:28,656  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 19:59:32,800  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 19:59:36,875  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:06:48,700  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:06:52,818  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:26:47,275  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:26:51,402  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:34:12,564  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:34:16,752  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:34:20,842  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:34:24,925  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:34:27,930 ERROR [Replication Processor] dtv.data2.replication.dtximpl.ReplicationProcessor - Unpexpected exception caught in ReplicationProcessor main loop. We will attempt to continue.
dtv.data2.replication.ReplicationException: Unable to obtain datasource for replication queue [Replication]
	at dtv.data2.replication.dtximpl.ReplicationQueueAccessor.getConnection(ReplicationQueueAccessor.java:614) ~[dtv-data2.jar:22.0.0.0.20230127185818]
	at dtv.data2.replication.dtximpl.ReplicationQueueAccessor.queryNonFailedRecCount(ReplicationQueueAccessor.java:294) ~[dtv-data2.jar:22.0.0.0.20230127185818]
	at dtv.data2.replication.dtximpl.ReplicationProcessor.run(ReplicationProcessor.java:172) ~[dtv-data2.jar:22.0.0.0.20230127185818]
2023-07-09 20:44:34,914  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:44:38,993  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 20:44:43,069  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:02:30,095  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:02:34,231  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:02:38,328  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:07:55,763  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:07:59,862  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:08:03,945  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:08:08,026  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:08:11,042 ERROR [Replication Processor] dtv.data2.replication.dtximpl.ReplicationProcessor - Unpexpected exception caught in ReplicationProcessor main loop. We will attempt to continue.
dtv.data2.replication.ReplicationException: Unable to obtain datasource for replication queue [Replication]
	at dtv.data2.replication.dtximpl.ReplicationQueueAccessor.getConnection(ReplicationQueueAccessor.java:614) ~[dtv-data2.jar:22.0.0.0.20230127185818]
	at dtv.data2.replication.dtximpl.ReplicationQueueAccessor.queryNonFailedRecCount(ReplicationQueueAccessor.java:294) ~[dtv-data2.jar:22.0.0.0.20230127185818]
	at dtv.data2.replication.dtximpl.ReplicationProcessor.run(ReplicationProcessor.java:172) ~[dtv-data2.jar:22.0.0.0.20230127185818]
2023-07-09 21:10:54,923  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:10:59,092  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:46:54,505  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:46:58,649  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:47:02,736  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:47:06,832  WARN [Replication Processor] dtv.data2.replication.dtximpl.ReplicationQueueAccessor - A failover occurred while obtaining replication queue datasource. [Replication] dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

2023-07-09 21:47:09,832 ERROR [Replication Processor] dtv.data2.replication.dtximpl.ReplicationProcessor - Unpexpected exception caught in ReplicationProcessor main loop. We will attempt to continue.
dtv.data2.replication.ReplicationException: Unable to obtain datasource for replication queue [Replication]
	at dtv.data2.replication.dtximpl.ReplicationQueueAccessor.getConnection(ReplicationQueueAccessor.java:614) ~[dtv-data2.jar:22.0.0.0.20230127185818]
	at dtv.data2.replication.dtximpl.ReplicationQueueAccessor.queryNonFailedRecCount(ReplicationQueueAccessor.java:294) ~[dtv-data2.jar:22.0.0.0.20230127185818]
	at dtv.data2.replication.dtximpl.ReplicationProcessor.run(ReplicationProcessor.java:172) ~[dtv-data2.jar:22.0.0.0.20230127185818]
